version: '3'
services:
  homeassistant:
    container_name: home_assistant
    image: "homeassistant/home-assistant:latest"
    volumes:
      - /Path/to/dir/ha_config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
